### ISSUE TITLE
For Debugger.GetExpression

### ISSUE THREAD

**Issue by ulinzeng** [rainliang000/VSIXCustomWatch#1]
Hello rainliang000,I am doing a project the same as yours.But,when I call Debugger.GetExpression,The returned expression is truncated,just like "file system...".Is there has another method to get more info about the expression?Thank you.

**Comment by ryanliang000** [comment]
Set the second param of Debugger.GetExpression, set it to true will not truncate returned string.

**Comment by ulinzeng** [comment]
But this is not useful. When the resulting expression exceeds a certain length (very short), the following expression will be truncated to three '.'

**Comment by ryanliang000** [comment]
You can use a returned pointer address to supported a long string.
